/**
 * File-backed run store — runs persist across server restarts and stay
 * visible until JJ archives them (his "published, done" signal).
 *
 * Layout: .runs/<runId>/
 *   meta.json      — status, brief, drafts, science, proposal, summary
 *   events.ndjson  — every RunEvent, appended live (UI replay)
 *   messages.json  — the Anthropic conversation (legs resume from here)
 *
 * Local single-operator shell: files are the right database (Phase 2's
 * remote control-plane swaps this for a shared store).
 */
import { mkdirSync, existsSync, readFileSync, writeFileSync, appendFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import type Anthropic from "@anthropic-ai/sdk";
import type { CreatedDraft, Proposal, RunEvent, ScienceEntry } from "./types";

const RUNS_DIR = join(process.cwd(), ".runs");

export type RunStatus = "running" | "awaiting-jj" | "done" | "error" | "archived";

export interface RunMeta {
    runId: string;
    skill: string;
    /** Model for this run (older runs may lack it — fall back to config). */
    model?: string;
    brief: string;
    title: string;
    status: RunStatus;
    createdAt: string;
    updatedAt: string;
    drafts: CreatedDraft[];
    science: ScienceEntry[];
    criticsCleared: boolean;
    proposalApproved: boolean;
    proposal: Proposal | null;
    summary: string | null;
    turnsUsed: number;
}

const dir = (runId: string) => join(RUNS_DIR, runId);
const metaPath = (runId: string) => join(dir(runId), "meta.json");
const eventsPath = (runId: string) => join(dir(runId), "events.ndjson");
const messagesPath = (runId: string) => join(dir(runId), "messages.json");

/** Guard: runId is generated by us (uuid) — never accept path separators. */
const assertSafeId = (runId: string) => {
    if (!/^[a-zA-Z0-9-]+$/.test(runId)) throw new Error(`Invalid runId "${runId}"`);
};

export function initRun(meta: RunMeta, messages: Anthropic.MessageParam[]): void {
    assertSafeId(meta.runId);
    mkdirSync(dir(meta.runId), { recursive: true });
    saveMeta(meta);
    saveMessages(meta.runId, messages);
    writeFileSync(eventsPath(meta.runId), "");
}

export function runExists(runId: string): boolean {
    assertSafeId(runId);
    return existsSync(metaPath(runId));
}

export function loadMeta(runId: string): RunMeta {
    assertSafeId(runId);
    return JSON.parse(readFileSync(metaPath(runId), "utf8")) as RunMeta;
}

export function saveMeta(meta: RunMeta): void {
    meta.updatedAt = new Date().toISOString();
    writeFileSync(metaPath(meta.runId), JSON.stringify(meta, null, 1));
}

export function loadMessages(runId: string): Anthropic.MessageParam[] {
    assertSafeId(runId);
    return JSON.parse(readFileSync(messagesPath(runId), "utf8")) as Anthropic.MessageParam[];
}

export function saveMessages(runId: string, messages: Anthropic.MessageParam[]): void {
    writeFileSync(messagesPath(runId), JSON.stringify(messages));
}

export function appendEvent(runId: string, event: RunEvent): void {
    appendFileSync(eventsPath(runId), JSON.stringify(event) + "\n");
}

export function loadEvents(runId: string): RunEvent[] {
    assertSafeId(runId);
    if (!existsSync(eventsPath(runId))) return [];
    return readFileSync(eventsPath(runId), "utf8")
        .split("\n")
        .filter(Boolean)
        .map((line) => JSON.parse(line) as RunEvent);
}

/** All runs, newest first; archived last. */
export function listRuns(): RunMeta[] {
    if (!existsSync(RUNS_DIR)) return [];
    const metas: RunMeta[] = [];
    for (const entry of readdirSync(RUNS_DIR)) {
        try {
            metas.push(loadMeta(entry));
        } catch {
            /* skip corrupt/partial run dirs */
        }
    }
    return metas.sort((a, b) => {
        if ((a.status === "archived") !== (b.status === "archived")) {
            return a.status === "archived" ? 1 : -1;
        }
        return b.updatedAt.localeCompare(a.updatedAt);
    });
}

// One leg at a time per run — a second concurrent request is refused.
const activeLegs = new Set<string>();
export function acquireLeg(runId: string): boolean {
    if (activeLegs.has(runId)) return false;
    activeLegs.add(runId);
    return true;
}
export function releaseLeg(runId: string): void {
    activeLegs.delete(runId);
}
